Models/Meeting/ListRegistrUsersOnEvent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RolesApp.Models.Meeting
{
    public class ListRegistrUsersOnEvent
    {
        public int id { get; set; }
        public int IdUser { get; set; }
        public int IdMeeting { get; set; }
    }
}

Models/Meeting/MeetingInformation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RolesApp.Models.Meeting
{
    public class MeetingInformation
    {
        public int Id { get; set; }
        public int MeetingID { get; set; }
        public string Header { get; set; }
        public string Context { get; set; }
    }
}

Models/Meeting/MeetingModel.cs
                using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RolesApp.Models.Meeting
{
    public class MeetingModel
    {
        public string NameEvent { get; set; }

        public List<string> HeaderEvent { get; set; }

        public List<string> ContextEvent { get; set; }
    }
}

Models/Meeting/NameMeetingEvent.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace RolesApp.Models
{
    public class NameMeetingEvent
    {
        [Key]
        public int Id { get; set; }
        public string NameEvent { get; set; }
    }
}

Controllers/MeetingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RolesApp.Models;
using Microsoft.EntityFrameworkCore;
using RolesApp.Models.Meeting;
using Microsoft.VisualStudio.Web.CodeGeneration.Contracts.Messaging;

namespace RolesApp.Controllers
{
    public class MeetingController : Controller
    {
        private ApplicationContext _context;
        public MeetingController(ApplicationContext context)
        {
            _context = context;
        }

        [HttpGet]
        public ActionResult AddMeeting()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddMeeting(MeetingModel model)
        {
            NameMeetingEvent meeting = new NameMeetingEvent
            {
                NameEvent = model.NameEvent
            };
            _context.MeetingEvents.Add(meeting);
            _context.SaveChanges();

            int a = _context.MeetingEvents.Count();

            if (model.HeaderEvent.Count() > 0 && model.NameEvent.Count() > 0)
            {
                for (int i = 0; i < model.HeaderEvent.Count; i++)
                {
                    MeetingInformation information = new MeetingInformation
                    {
                        MeetingID = _context.MeetingEvents.Count(),
                        Header = model.HeaderEvent[i],
                        Context = model.ContextEvent[i]
                    };
                    _context.MeetingInformations.Add(information);
                    _context.SaveChanges();
                }
            }
            return RedirectToAction("GetAllMeeting");
        }

        [HttpGet]
        public IActionResult GetAllMeeting()
        {
            return View(_context.MeetingEvents.ToList());
        }

        public IActionResult GetInfoAboutMeeting(int? EventId)
        {
            NameMeetingEvent SelectedMeeting = _context.MeetingEvents.Single(p => p.Id == EventId);

            List<MeetingInformation> SelectedMeetingInfo = new List<MeetingInformation>();

            foreach(var element in _context.MeetingInformations)
            {
                if (element.MeetingID == SelectedMeeting.Id)
                {
                    SelectedMeetingInfo.Add(element);

                }
            }

            ViewBag.EventId = EventId; //I'm sorry for ViewBag :(
            return View(SelectedMeetingInfo);
        }

        public IActionResult RegistrationOnMeeting(int EventId)
        {
            bool isRegistered = false;
            string NameUser =  HttpContext.User.Identity.Name;
            ListRegistrUsersOnEvent record = new ListRegistrUsersOnEvent();
            foreach(var user in _context.Users)
            {
                if (user.Name == HttpContext.User.Identity.Name)
                    record.IdUser = user.Id;
            }
            record.IdMeeting = EventId;

            foreach(var user in _context.listRegistrUsersOnEvents)
            {
                if (record.IdUser == user.IdUser)
                    isRegistered = true;
 
            }
            if (!isRegistered)
            {
                _context.listRegistrUsersOnEvents.Add(record);
                _context.SaveChanges();
            }
            else
                Response.WriteAsync("<script>alert('You are registered on this Meeting!')</script>");
            return RedirectToAction("GetAllMeeting");
        }
    }
}

Views/Meeting/AddMeeting.cshtml
@{
    Layout = "_Layout";
}
<script src="~/lib/jquery/dist/jquery.js"></script>

<form method="post" asp-controller="Meeting" asp-action="AddMeeting" asp-anti-forgery="true">
    <p>Название мероприятия:</p>
    <div><input class="inputNameEvent" type="text" id="idtxt" name="NameEvent" /></div>
    <p>Тема---------------------------Подтема</p>
    <div>
        <input class="inputHeader" type="text" id="idtxt" name="HeaderEvent[0]" /> 
        <input class="inputContext" type="text" id="idtxt" name="ContextEvent[0]" />
        <p></p>
    </div>

    <div id="textboxDiv"></div>

    <script>
        $(document).ready(function () {
            $("#Add").on("click", function () {
                $("#textboxDiv").append("<input class='inputHeader' type='text' id='idtxt' name='HeaderEvent[" + document.getElementsByClassName('inputHeader').length + "]'/>  ");
                $("#textboxDiv").append("<input class='inputContext' type='text' id='idtxt' name='ContextEvent[" + document.getElementsByClassName('inputContext').length + "]'/>");
                $("#textboxDiv").append("<p><div></div></p>");
            });
            $("#Remove").on("click", function () {
                $("#textboxDiv").children().last().remove();
            });
        });
    </script>

    <button type="button" id="Add">Добавить поля</button>
    <button type="button" id="Remove">Удалить поля</button>

    <input type="submit" value="Отправить" />
</form>

Views/Meeting/GetAllMeeting.cshtml
@model IEnumerable<RolesApp.Models.NameMeetingEvent>
@{
    Layout = "_Layout";
}
<h3>Список мероприятий</h3>
@foreach (var item in Model)
{
    <p> @Html.ActionLink(item.NameEvent, "GetInfoAboutMeeting", "Meeting", new { EventId = item.Id }, null)</p>

}


Views/Meeting/GetInfoAboutMeeting.cshtml
@model IEnumerable<RolesApp.Models.Meeting.MeetingInformation>
@{
    Layout = "_Layout";
}
<h2>GetInfoAboutMeeting</h2>


@foreach (var item in Model)
{
    <p>
        <span>@item.Header</span>:
        <span>  @item.Context</span>
    </p>
}

@Html.ActionLink("Записаться", "RegistrationOnMeeting", "Meeting", new { EventId = ViewBag.EventId }, null)
@Html.ActionLink("Список участников", "ListRegistration", "Meeting", new { EventId = ViewBag.EventId }, null)